### ISSUE TITLE
autosome_only does not respect defaults in ld pruning

### ISSUE THREAD

**Issue by aofarrel** [UW-GAC/analysis_pipeline_cwl#4]
The SB tooltip indicates that autosome_only defaults to true, but that's not actually the case. In the context of the R script, yes, but not the CWL overall.

Expected behavior:
- User does not set autosome_only --> written to config as true OR not at all --> treated as true
- User sets autosome_only = true --> written to config as true OR not at all --> treated as true
- User sets autosome_only = false --> written to config as false --> treated as false

Actual behavior:
- User does not set autosome_only --> **written to config as false** --> **treated as false**
- User sets autosome_only = true --> not written to config at all --> treated as true
- User sets autosome_only = false --> written to config as false --> treated as false

Breakdown and probable cause here: https://github.com/DataBiosphere/analysis_pipeline_WDL/issues/8#issuecomment-861764803

**Comment by smgogarten** [comment]
Fixed in c2eb59b by setting default value in tool
