### ISSUE TITLE
kinship_method cannot be set in SB UI

### ISSUE THREAD

**Issue by aofarrel** [UW-GAC/analysis_pipeline_cwl#7]
Although kinship_method exists as a task level input here...

https://github.com/UW-GAC/analysis_pipeline_cwl/blob/6e654f798a18c25a5fdba923c52588724a19dd35/relatedness/tools/kinship_plots.cwl#L59

It is not exposed on the workflow level, nor does it appear in the Seven Bridges UI.

**Comment by smgogarten** [comment]
This is intentional. kinship_plots is a tool shared by several workflows, but each workflow has only one valid value for this input ([example](https://github.com/UW-GAC/analysis_pipeline_cwl/blob/6e654f798a18c25a5fdba923c52588724a19dd35/relatedness/pc-relate-wf.cwl#L228))
